export const ActionTypes = {
  //templates
  SET_TEMPLATES: 'SET_TEMPLATES',
  SELECTED_TEMPLATE: 'SELECTED_TEMPLATE',
  SET_SEARCH_RESULTS_TEMPLATES: 'SET_SEARCH_RESULTS_TEMPLATES',

  //pdf
  SET_PDFS: 'SET_PDFS',
  SELECTED_PDF: 'SELECTED_PDF',
}
